/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreviewMetaRouteImport } from './routes/preview-meta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawdownIndexRouteImport } from './routes/drawdown/index'
import { Route as DrawdownDdRouteImport } from './routes/drawdown/$dd'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewMetaRoute = PreviewMetaRouteImport.update({
  id: '/preview-meta',
  path: '/preview-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawdownIndexRoute = DrawdownIndexRouteImport.update({
  id: '/drawdown/',
  path: '/drawdown/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawdownDdRoute = DrawdownDdRouteImport.update({
  id: '/drawdown/$dd',
  path: '/drawdown/$dd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview-meta': typeof PreviewMetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/drawdown/$dd': typeof DrawdownDdRoute
  '/drawdown/': typeof DrawdownIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview-meta': typeof PreviewMetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/drawdown/$dd': typeof DrawdownDdRoute
  '/drawdown': typeof DrawdownIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview-meta': typeof PreviewMetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/drawdown/$dd': typeof DrawdownDdRoute
  '/drawdown/': typeof DrawdownIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview-meta'
    | '/sitemap.xml'
    | '/drawdown/$dd'
    | '/drawdown/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview-meta' | '/sitemap.xml' | '/drawdown/$dd' | '/drawdown'
  id:
    | '__root__'
    | '/'
    | '/preview-meta'
    | '/sitemap.xml'
    | '/drawdown/$dd'
    | '/drawdown/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewMetaRoute: typeof PreviewMetaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DrawdownDdRoute: typeof DrawdownDdRoute
  DrawdownIndexRoute: typeof DrawdownIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-meta': {
      id: '/preview-meta'
      path: '/preview-meta'
      fullPath: '/preview-meta'
      preLoaderRoute: typeof PreviewMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawdown/': {
      id: '/drawdown/'
      path: '/drawdown'
      fullPath: '/drawdown/'
      preLoaderRoute: typeof DrawdownIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawdown/$dd': {
      id: '/drawdown/$dd'
      path: '/drawdown/$dd'
      fullPath: '/drawdown/$dd'
      preLoaderRoute: typeof DrawdownDdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewMetaRoute: PreviewMetaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DrawdownDdRoute: DrawdownDdRoute,
  DrawdownIndexRoute: DrawdownIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
